DROP FUNCTION SALARIO_ANUAL; 
CREATE OR REPLACE FUNCTION SALARIO_ANUAL (SALAR EMP.SAL%TYPE, COMISION EMP.COMM%TYPE)
RETURN NUMBER
IS 
	V_SAL EMP.SAL%TYPE:=0; 
BEGIN	
	V_SAL:=(SALAR+NVL(COMISION,0))*12;
	DBMS_OUTPUT.PUT_LINE(V_SALA); 
	RETURN V_SAL; 
END SALARIO_ANUAL;
/