CREATE OR REPLACE TYPE TELEFONO AS OBJECT(
    TIPO VARCHAR(30),
    NUMERO NUMBER
);
/

CREATE OR REPLACE TYPE LISTIN AS TABLE OF TELEFONO;
/

DROP TABLE CLIENTES3;
CREATE TABLE CLIENTES3(
    ID_CLI NUMBER,
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    DIRECCION VARCHAR(30),
    POBLACION VARCHAR(30),
    PROVINCIA VARCHAR(30),
    TELEFONOS LISTIN)
    NESTED TABLE TELEFONOS STORE AS TEL_TAB
/

INSERT INTO CLIENTES3 VALUES(
    1,'FERNANDO','MORENO','CALLE MANANTIAL 50','MADRID','MADRID',
    LISTIN(
        TELEFONO('MOVIL',626089187),
        TELEFONO('TRABAJO',626209384),
        TELEFONO('FIJO',364738473)));

INSERT INTO CLIENTES3 VALUES(
    2,'ALVARO','GUTIERREZ','CALLE LAS GÓNDOLAS 2','SEVILLA','SEVILLA',
    LISTIN(
        TELEFONO('MOVIL',6234532453),
        TELEFONO('TRABAJO',626203484),
        TELEFONO('FIJO',364732273)));

INSERT INTO CLIENTES3 VALUES(
    3,'LAURA','PEY','CALLE AGUA 5','MADRID','MADRID',
    LISTIN(
        TELEFONO('MOVIL',626089187),
        TELEFONO('TRABAJO',626349384),
        TELEFONO('FIJO',364732173)));
        
SELECT * FROM CLIENTES3;

SELECT SEGMENT_NAME, SEGMENT_TYPE FROM USER_SEGMENTS WHERE SEGMENT_NAME LIKE '%TEL_TAB%';

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM ALL_OBJECTS WHERE OBJECT_NAME LIKE '%TEL_TAB%';

SELECT * FROM USER_NESTED_TABLES; 

SELECT T.* FROM CLIENTES3 C, TABLE(C.TELEFONOS) T WHERE C.ID_CLI=3;

UPDATE CLIENTES3 SET TELEFONOS =LISTIN(
    TELEFONO('FIJO',934444444),
    TELEFONO('MOVIL PERSONAL',655555555),
    TELEFONO('MOVIL EMPRESA',644444444)
)WHERE ID_CLI=1;

SELECT T.* FROM CLIENTES3 C, TABLE(C.TELEFONOS) T;

SELECT C.NOMBRE, C.ID_CLI, T.*
FROM CLIENTES3 C, TABLE(C.TELEFONOS) T;