CREATE TYPE TIPO_NOMBRES_DEP IS VARRAY(7) OF VARCHAR(30);
/
CREATE TABLE DEPARTAMENTOS(REGION VARCHAR (25), NOMBRES_DEP TIPO_NOMBRES_DEP);

INSERT INTO DEPARTAMENTOS VALUES('EUROPA',TIPO_NOMBRES_DEP('SHIPPING','PAYROLL','SALES','FINANCES'));

SET SERVEROUTPUT ON;

DECLARE
	V_NOMBRES TIPO_NOMBRES_DEP:=TIPO_NOMBRES_DEP('BENEFITS','ADVERTISING','CONTRACTING','EXECUTIVE','MARKETING');
	V_NOMBRES2 TIPO_NOMBRES_DEP;
BEGIN
	UPDATE DEPARTAMENTOS SET NOMBRES_DEP=V_NOMBRES
	WHERE REGION='EUROPA';
	COMMIT;
 
	SELECT NOMBRES_DEP INTO V_NOMBRES2 FROM DEPARTAMENTOS WHERE REGION='EUROPA';
	FOR I IN V_NOMBRES2.FIRST .. V_NOMBRES2.LAST LOOP
	DBMS_OUTPUT.PUT_LINE('DEPARTAMENTOS: '||V_NOMBRES2(I));
	END LOOP;
END;
/

DECLARE
	CURSOR C_DEPT IS SELECT * FROM DEPARTAMENTOS;
	V_REGION VARCHAR(25);
	V_NOMBRES TIPO_NOMBRES_DEP;
BEGIN
	OPEN C_DEPTS;

	LOOP 
		FETCH C_DEPTS INTO V_REGION, V_NOMBRES;
		EXIT WHEN C_DEPTS%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE('REGION '||V_REGION);
		FOR I IN V_NOMBRES.FIRST.. V_NOMBRES.LAST LOOP
			DBMS_OUTPUT.PUT_LINE('DEPARTAMENTO ('||I||')'||V_NOMBRES(I));
		END LOOP;
	END LOOP;
END;
/

DECLARE 
	CURSOR V_ZONAS IS SELECT * FROM DEPARTAMENTOS;
BEGIN
	FOR I IN V_ZONAS LOOP
		DBMS_OUTPUT.PUT_LINE('REGION '||V_REGION);
		FOR J IN I.NOMBRES_DEP.FIRST.. I.NOMBRES_DEP.LAST LOOP
			DBMS_OUTPUT.PUT_LINE('DEPARTAMENTO ('||I||')'||I.NOMBRES_DEP(J));
		END LOOP;
	END LOOP;
END;
/