CREATE OR REPLACE TYPE TABLA_ANIDADA AS TABLE OF DIRECCION;
/
CREATE TABLE EJEMPLO_TABLA_ANIDADA(
    ID NUMBER(2),
    APELLIDO VARCHAR2(35),
    DIREC TABLA_ANIDADA)
    NESTED TABLE DIREC STORE AS DIREC_ANIDADA;

INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES(1,'RAMOS',TABLA_ANIDADA(
    DIRECCION('CALLE MANANTIALES 2','GUADALAJARA', 19984),
    DIRECCION('CALLE MANANTIALES 2','GUADALAJARA', 19982),
    DIRECCION('CALLE MANANTIALES 3','GUADALAJARA', 19983),
    DIRECCION('CALLE MANANTIALES 4','GUADALAJARA', 19984),
    DIRECCION('CALLE MANANTIALES 5','GUADALAJARA', 19985))
);
INSERT INTO EJEMPLO_TABLA_ANIDADA VALUES(2,'MARTIN',TABLA_ANIDADA(
    DIRECCION('CALLE HUESCA 2','ALCALÁ D EHENARES', 28008),
    DIRECCION('CALLE MANANTIALES 22','GUADALAJARA', 19982),
    DIRECCION('CALLE MANANTIALES 13','GUADALAJARA', 19983))
);

SELECT E.DIREC FROM EJEMPLO_TABLA_ANIDADA E WHERE E.ID=1;

SELECT DIR.CALLE FROM EJEMPLO_TABLA_ANIDADA E, TABLE(E.DIREC) DIR 
WHERE E.ID=1;

UPDATE TABLE(SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID=1)PRIMERA
SET VALUE(PRIMERA)=DIRECCION('C/Pinzon 13','TOLEDO',45555)
WHERE VALUE(PRIMERA)=DIRECCION('CALLE MANANTIALES 22','GUADALAJARA',19982);

SELECT E.DIREC FROM EJEMPLO_TABLA_ANIDADA E WHERE E.ID=1;

INSERT INTO TABLE(SELECT E.DIREC FROM EJEMPLO_TABLA_ANIDADA E WHERE ID=1)
VALUES(DIRECCION('CALLE LOS NARANJOS, 99','MURCIA',78788));

SELECT DIREC FROM EJEMPLO_TABLA_ANIDADA WHERE ID=1;
SELECT DIR.* FROM EJEMPLO_TABLA_ANIDADA E, TABLE(E.DIREC) DIR WHERE E.ID=1;

UPDATE EJEMPLO_TABLA_ANIDADA SET DIREC=TABLA_ANIDADA(DIRECCION('CALLE SOL','MADIRD',280022))
WHERE ID=1;

DELETE FROM TABLE(SELECT E.DIREC FROM EJEMPLO_TABLA_ANIDADA E WHERE ID=1) PRIMERA 
WHERE VALUE (PRIMERA)=DIRECCION('CALLE LOS NARANJOS,99','MURCIA',78788);

SELECT CALLE FROM THE(SELECT E.DIREC FROM EJEMPLO_TABLA_ANIDADA E WHERE=1)WHERE CIUDAD = 'Murcia';

SELECT DIR.CALLE FROM EJEMPLO_TABLA_ANIDADA E, TABLE(E.DIREC) DIR WHERE E.ID=1 AND DIR.CIUDAD='MURCIA';

CREATE OR REPLACE PROCEDURE VER_DIREC(IDENT NUMBER) 
AS 
    CURSOR C1 IS SELECT FROM THE(SELECT E.DIREC FROM EJEMPLO_TABLA_ANIDADA E WHERE E.ID=IDENT);
BEGIN
    FOR I IN C1 LOOP
        DBMS_OUTPUT.PUT_LINE(I.CALLE);
    END LOOP;
END;
/

SET SERVEROUTPUT ON;

BEGIN
    VER_DIREC(1);
END;
/

CREATE OR REPLACE PROCEDURE VER_DIREC2(IDENT NUMBER) 
AS 
    CURSOR C1 IS 
        SELECT FROM THE(SELECT DIR.CALLE FROM EJEMPLO_TABLA_ANIDADA E TABLE(E.DIREC) DIR 
        WHERE E.ID=IDENT);
BEGIN
    FOR I IN C1 LOOP
        DBMS_OUTPUT.PUT_LINE(I.CALLE);
    END LOOP;
END;
/

BEGIN
    VER_DIREC2(1)
END;
/