CREATE OR REPLACE TYPE TIPO_CUBO AS OBJECT(
	LARGO INTEGER,
	ANCHO INTEGER,
	ALTO INTEGER,
	MEMBER FUNCTION SUPERFICIE RETURN INTEGER, 
	MEMBER FUNCTION VOLUMEN RETURN INTEGER,
	MEMBER PROCEDURE MOSTRAR);
/

CREATE OR REPLACE TYPE BODY TIPO_CUBO 
AS
	MEMBER FUNCTION SUPERFICIE RETURN INTEGER 
	IS
	BEGIN
		RETURN 2*(LARGO*ANCHO+LARGO*ALTO+ANCHO*ALTO);
	END;

	MEMBER FUNCTION VOLUMEN RETURN INTEGER 
	IS
	BEGIN
		RETURN (LARGO*ALTO*ANCHO);
	END;

	MEMBER PROCEDURE MOSTRAR
	IS
	BEGIN
		DBMS_OUTPUT.PUT_LINE(' LARGO: '||LARGO||' ANCHO: '||ANCHO||' ALTO: '||ALTO);
		DBMS_OUTPUT.PUT_LINE('VOLUMEN: '||VOLUMEN|| 'SUPERFICIE: '||SUPERFICIE);
	END;
END;
/

DROP TABLE CUBOS;
CREATE TABLE CUBOS OF TIPO_CUBO;

INSERT INTO CUBOS VALUES (TIPO_CUBO(10,10,10));
INSERT INTO CUBOS VALUES (TIPO_CUBO(3,4,5));

INSERT INTO CUBOS VALUES (3,4,7);

SELECT * FROM CUBOS;
SELECT C.VOLUMEN(), C.SUPERFICIE() FROM CUBOS C WHERE C.LARGO=10;

DECLARE
	MI_CUBO TIPO_CUBO;
BEGIN
	SELECT VALUE(C) INTO MI_CUBO FROM CUBOS C WHERE C.LARGO=10;
	MI_CUBO.MOSTRAR();
END;
/