DROP TABLE STAFF;
CREATE OR REPLACE TYPE TABLA_HIJOS AS TABLE OF VARCHAR(30);
/
CREATE TABLE STAFF(
    ID NUMBER,
    NOMBRE VARCHAR(30),
    APELLIDOS VARCHAR(30),
    HIJOS TABLA_HIJOS)
    NESTED TABLE HIJOS STORE AS T_HIJOS
/

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM ALL_OBJECTS WHERE OBJECT_NAME LIKE '%HIJO%';

SELECT SEGMENT_NAME, SEGMENT_TYPE FROM USER_SEGMENTS WHERE SEGMENT_NAME LIKE '%HIJO%';

INSERT INTO STAFF VALUES(1,'FERNANDO','MORENO',TABLA_HIJOS('ELENA','PABLO'));
INSERT INTO STAFF VALUES(2,'DAVID','SANCHEZ',TABLA_HIJOS('CARMEN','CANDELA'));

SELECT * FROM THE(SELECT S.HIJOS FROM STAFF S WHERE S.ID=1);

SELECT ST.* FROM STAFF S, TABLE(S.HIJOS)ST WHERE S.ID=1; /*CON TABLE*/

UPDATE STAFF SET HIJOS =TABLA_HIJOS('CARMEN','CANDELA','CAYETANA') WHERE ID=1;

SELECT ST.* FROM STAFF S, TABLE(S.HIJOS)ST WHERE S.ID=1 OR S.ID=2;