DROP TABLE CLIENTE;
CREATE TABLE CLIENTE(
    IDCLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(30),
    DIRECCION VARCHAR2(30),
    POBLACION VARCHAR2(30),
    CDPOSTAL VARCHAR(30),
    PROVINCIA VARCHAR2(30),
    NIF VARCHAR2(10),
    TEL1 NUMBER(9),
    TEL2 NUMBER(9),
    TEL3 NUMBER(9)
);

DROP TABLE PRODUCTOS;
CREATE TABLE PRODUCTOS(
    IDPRODUCTO NUMBER PRIMARY KEY, 
    DESCRIPCION VARCHAR2(10),
    PVP NUMBER,
    STOCKACTUAL NUMBER
);

CREATE TABLE VENTAS(
    IDVENTAS NUMBER PRIMARY KEY,
    IDCLIENTE NUMBER,
    FECHAVENTA DATE
);

DROP TABLE LINEASVENTAS;
CREATE  TABLE LINEASVENTAS(
    IDVENTA NUMBER,
    NUMEROLINEA NUMBER,
    IDPRODUCTO NUMBER,
    CANTIDAD NUMBER,
    CONSTRAINT PK_LINEASVENTAS PRIMARY KEY(IDVENTA, NUMEROLINEA)
);

