CREATE OR REPLACE TYPE TIP_DIREC AS
    OBJECT(
        DIR VARCHAR2(30),
        COD_POSTAL VARCHAR2(30)
    );
/

CREATE OR REPLACE TYPE TIPO_CONTACTO AS
    OBJECT(
        TLF NUMBER,
        EMAIL VARCHAR2(30)
    );
/

CREATE OR REPLACE TYPE TIPO_PERSONA AS
    OBJECT(
        ID NUMBER,
        NOMBRE VARCHAR2(30),
        APELLIDO VARCHAR2(30),
        DIREC TIP_DIREC,
        CONTACT TIPO_CONTACTO
    ) NOT FINAL
/

CREATE OR REPLACE TYPE TIP_CLIENT UNDER TIPO_PERSONA(
    N_PEDIDOS NUMBER
);
/

CREATE OR REPLACE TYPE TIPO_ART AS
    OBJECT(
        ID NUMBER,
        NOMBRE VARCHAR2(30),
        DESCRIPCION VARCHAR2(30),
        PRECIO NUMBER,
        PORCENTAJE NUMBER
    );
/

CREATE OR REPLACE TYPE TAB_ARTICULO AS
    TABLE OF TIPO_ART;
/

CREATE OR REPLACE TYPE TIP_LDETALLE AS
    OBJECT(
        NUMERO NUMBER,
        ARTICLO TIPO_ART,
        CANTIDAD NUMBER
    );
/

CREATE OR REPLACE TYPE TAB_DETALLE AS
    TABLE OF TIP_LDETALLE;
/

CREATE OR REPLACE TYPE TIP_LCOMPRA AS
    OBJECT(
        ID NUMBER,
        FECHA DATE,
        CLI REF TIP_CLIENT,
        DETALLE TAB_DETALLE,
        MEMBER FUNCTION TOTAL_LISTA RETURN NUMBER
    );
/

CREATE OR REPLACE TYPE BODY TIP_LCOMPRA AS
    MEMBER FUNCTION TOTAL_LISTA RETURN NUMBER IS
        I   INTEGER;
        TOT NUMBER:=0;
    BEGIN
        FOR I IN 1.. DETALLE.COUNT LOOP
            TOT:=TOT+(DETALLE(I).ARTICLO.PRECIO*DETALLE(I).CANTIDAD)* (1+(DETALLE(I).ARTICLO.PORCENTAJE/100));
        END LOOP;
        RETURN TOT;
    END;
END;
/

CREATE TABLE CLIENTS OF TIP_CLIENT;

INSERT INTO CLIENTS VALUES(
    '1',
    'MIGUEL',
    'FREEMAN',
    TIP_DIREC('GUAREÑA', '28044'),
    TIPO_CONTACTO(626089187, 'GMAIL'),
    0
);

INSERT INTO CLIENTS VALUES(
    '2',
    'ILLIDAN',
    'STORMRAGE',
    TIP_DIREC('BLACK TEMPLE', '50150'),
    TIPO_CONTACTO(626089333, 'GMAIL'),
    0
);

CREATE TABLE LISTIYAS OF TIP_LCOMPRA NESTED TABLE DETALLE STORE AS TDETALLE;

INSERT INTO LISTIYAS VALUES(
    1,
    SYSDATE,
    (SELECT REF(C) FROM CLIENTS C WHERE C.ID=1),
    TAB_DETALLE( TIP_LDETALLE( 1, TIPO_ART(1, 'CHORIZO', 'CURADO', 2, 5), 2), TIP_LDETALLE( 2, TIPO_ART(2, 'ARROZ', 'BOMBA', 3, 5), 2) )
);

SELECT * FROM LISTIYAS;

SELECT C.ID, C.TOTAL_LISTA() FROM LISTIYAS C;

SELECT D.ARTICLO.ID, D.ARTICLO.NOMBRE FROM LISTIYAS L, TABLE(L.DETALLE)D;