CREATE OR REPLACE TYPE VETERINARIO AS OBJECT (
    ID VARCHAR2(30),
    NOMBRE VARCHAR2(30),
    DIRECCION VARCHAR2(30)
);
/

CREATE OR REPLACE TYPE MASCOTA AS OBJECT(
    ID VARCHAR2(30),
    RAZA VARCHAR2(30),
    NOMBRE VARCHAR2(30),
    VET REF VETERINARIO
);
/

CREATE TABLE VETERINARIOS OF VETERINARIO;

CREATE TABLE MASCOTAS OF MASCOTA;

INSERT INTO VETERINARIOS VALUES('1','JESUS PEREZ','MAREO');

INSERT INTO MASCOTAS VALUES('1','PERRO','SPROKET',(
    SELECT REF(V) FROM VETERINARIOS V WHERE ID='1')
    );

SELECT M.* FROM MASCOTAS M;

SELECT M.ID, M.RAZA, M.NOMBRE, DEREF(VET) FROM MASCOTAS M;

DELETE VETERINARIOS;
DELETE MASCOTAS;
DROP TABLE MASCOTAS;
DROP TABLE VETERINARIOS;