CREATE OR REPLACE TYPE TIP_TRIANGLE AS
    OBJECT(
        BASE NUMBER,
        ALTURA NUMBER,
        MEMBER FUNCTION AREA RETURN NUMBER
    );
/

CREATE OR REPLACE TYPE BODY TIP_TRIANGLE AS
    MEMBER FUNCTION AREA RETURN NUMBER IS
    BEGIN
        RETURN (BASE*ALTURA)/2;
    END;
END;
/

CREATE TABLE TRIANGULOS(
    ID NUMBER,
    TRIANGULO TIP_TRIANGLE
);

INSERT INTO TRIANGULOS VALUES(
    1,
    TIP_TRIANGLE(3,4)
);

SELECT * FROM TIP_TRIANGLE;