CREATE OR REPLACE TYPE COLEC_TIPO_NOMBRES_DEPT AS VARRAY(7) OF VARCHAR(30);
/

CREATE TABLE DEPART(
    REGION VARCHAR(25),
    NOMBRES_DEPT COLEC_TIPO_NOMBRES_DEPT
);

INSERT INTO DEPART VALUES(
    'AFRICA',
    COLEC_TIPO_NOMBRES_DEPT(
        'SHIPPING','SALES','FINANCES'
    ));

SELECT DEPART.NOMBRES_DEPT FROM DEPART; 

DECLARE
    VCOLEC COLEC_TIPO_NOMBRES_DEPT:=COLEC_TIPO_NOMBRES_DEPT(
        'BENEFITS','ADVERTISING','contracting','executive','marketing');
    VNOMBRES COLEC_TIPO_NOMBRES_DEPT;
BEGIN
    UPDATE DEPART
    SET DEPART.NOMBRES_DEPT = VCOLEC
    WHERE REGION='EUROPA';

    SELECT NOMBRES_DEPT INTO VNOMBRES FROM DEPART WHERE REGION='EUROPA';

    FOR I IN VNOMBRES.FIRST .. VNOMBRES.LAST LOOP
        DBMS_OUTPUT.PUT_LINE(VNOMBRES(I));
    END LOOP;
END;
/

DECLARE
    CURSOR C IS SELECT * FROM ;
BEGIN 

END;
/