CREATE TABLESPACE "APPEMPLEADOS" LOGGING 
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\APPEMP.dbf' SIZE 24M 
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


DROP USER emple CASCADE;

CREATE USER emple IDENTIFIED BY emple
       DEFAULT TABLESPACE APPEMPLEADOS  
       TEMPORARY TABLESPACE temp
       ACCOUNT UNLOCK;

GRANT "CONNECT" TO emple;
GRANT "RESOURCE" TO emple;

GRANT ALTER ANY INDEX TO emple;
GRANT ALTER ANY SEQUENCE TO emple;
GRANT ALTER ANY TABLE TO emple;
GRANT ALTER ANY TRIGGER TO emple;
GRANT CREATE ANY INDEX TO emple;
GRANT CREATE ANY SEQUENCE TO emple;
GRANT CREATE ANY SYNONYM TO emple;
GRANT CREATE ANY TABLE TO emple;
GRANT CREATE ANY TRIGGER TO emple;
GRANT CREATE ANY VIEW TO emple;
GRANT CREATE PROCEDURE TO emple;
GRANT CREATE PUBLIC SYNONYM TO emple;
GRANT CREATE TRIGGER TO emple;
GRANT CREATE VIEW TO emple;
GRANT DELETE ANY TABLE TO emple;
GRANT DROP ANY INDEX TO emple;
GRANT DROP ANY SEQUENCE TO emple;
GRANT DROP ANY TABLE TO emple;


