INSERT INTO HABILIDAD (NOMBRE, DESCRIPCION)
VALUES (
    'PARARRAYOS',
    'ATAQUES ELECTRICOS RECIBIDOS NO DAÑAN, +1 SP.ATK'
  );

INSERT INTO HABILIDAD (NOMBRE, DESCRIPCION)
VALUES (
    'PRESION',
    'ATAQUES ENEMIGOS CONSUMEN EL DOBLE DE PP'
  );

INSERT INTO HABILIDAD (NOMBRE, DESCRIPCION)
VALUES (
    'INTIMIDACION',
    'AL SALIR AL COMBATE -1 AL ATAQUE ENEMIGO'
  );

INSERT INTO HABILIDAD (NOMBRE, DESCRIPCION)
VALUES (
    'FUERZA MENTAL',
    'INMUNE A AMEDRENTARSE'
  );

INSERT INTO HABILIDAD (NOMBRE, DESCRIPCION)
VALUES (
    'ROMPEMOLDES',
    'IGNORA HAB. ENEMIGA QUE IMPIDA DAÑO O EFECTO'
  );

INSERT INTO HABILIDAD (NOMBRE, DESCRIPCION)
VALUES (
    'MOMIA',
    'HAB. ENEMIGA ES MOMIA AL RECIBIR CONTACTO'
  );

INSERT INTO HABILIDAD (NOMBRE, DESCRIPCION)
VALUES (
    'BROMISTA',
    'ATAQUES DE ESTADO AUMENTA EN 1 SU PRIORIDAD'
  );

INSERT INTO HABILIDAD (NOMBRE, DESCRIPCION)
VALUES (
    'CUERPO AUREO',
    'IMPIDE RECIBIR ATAQUES DE ESTADO'
  );

INSERT INTO HABILIDAD (NOMBRE, DESCRIPCION)
VALUES (
    'TABLILLA DEBACLE',
    '-25% EL ATAQUE DEL CAMPO'
  );

INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (25, 'PIKACHU', 'ELECTRICO', NULL, 'PARARRAYOS', 'KANTO', 0.4, 6.0);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (249, 'LUGIA', 'PSIQUICO', 'VOLADOR', 'PRESION', 'JOHTO', 5.2, 216.0);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (373, 'SALAMENCE', 'DRAGON', 'VOLADOR', 'INTIMIDACION', 'HOENN', 1.5, 102.6);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (448, 'LUCARIO', 'LUCHA', 'ACERO', 'FUERZA MENTAL', 'SINNOH', 1.2, 54.0);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (530, 'EXCADRILL', 'TIERRA', 'ACERO', 'ROMPEMOLDES', 'UNOVA', 0.7, 40.4);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (563, 'COFAGRIGUS', 'FANTASMA', NULL, 'MOMIA', 'UNOVA', 1.7, 76.5);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (727, 'INCINEROAR', 'FUEGO', 'SINIESTRO', 'INTIMIDACION', 'ALOLA', 1.8, 83.0);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (823, 'CORVIKNIGHT', 'VOLADOR', 'ACERO', 'PRESION', 'GALAR', 2.2, 75.0);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (861, 'GRIMMSNARL', 'SINIESTRO', 'HADA', 'BROMISTA', 'GALAR', 1.5, 61.0);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (1000, 'GOLDENGHO', 'ACERO', 'FANTASMA', 'CUERPO AUREO', 'PALDEA', 1.2, 30.0);
INSERT INTO POKEMON (ENTRADA, NOMBRE, TIPO_PRINCIPAL, TIPO_SECUNDARIO, HABILIDAD, REGION, ALTURA, PESO) VALUES (1001, 'WO-CHIEN', 'SINIESTRO', 'PLANTA', 'TABLILLA DEBACLE', 'PALDEA', 1.5, 74.2);