/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rittz.capota;

/**
 *
 * @author Rittz
 */
public class Capota extends javax.swing.JFrame {
    
    //attributes
    private String mensajeFijoVehiculo = "Has seleccionado un/a ";
    private String mensajeFinalVehiculo = "";
    private String cabeceraExtras = "Extras:";
    private String mensajeRemolque = "\t· Remolque";
    private String mensajeCapota = "\t· Capota";
    private String mensajeSidecar = "\t· Sidecar";
    private String alertFuel = "Debes seleccionar al menos un tipo de combustible antes de continuar";
        
    

    /**
     * Creates new form Capota
     */
    public Capota() {
        initComponents();
        jTextFieldAlertMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFuel = new javax.swing.ButtonGroup();
        labelTitle = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        labelModel = new javax.swing.JLabel();
        textBrand = new javax.swing.JTextField();
        textModel = new javax.swing.JTextField();
        labelVehicleType = new javax.swing.JLabel();
        labelExtras = new javax.swing.JLabel();
        checkBoxCoche = new javax.swing.JCheckBox();
        checkBoxMoto = new javax.swing.JCheckBox();
        checkBoxCamion = new javax.swing.JCheckBox();
        checkBoxCapota = new javax.swing.JCheckBox();
        checkBoxSidecar = new javax.swing.JCheckBox();
        checkBoxRemolque = new javax.swing.JCheckBox();
        jButtonSend = new javax.swing.JButton();
        jRadioButtonGasolina = new javax.swing.JRadioButton();
        jRadioButtonDiesel = new javax.swing.JRadioButton();
        jRadioButtonElectrico = new javax.swing.JRadioButton();
        jComboBoxColor = new javax.swing.JComboBox<>();
        jTextFieldAlertMessage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setText("Alquiler de vehículos");
        labelTitle.setName(""); // NOI18N

        brandLabel.setText("Marca:");

        labelModel.setText("Modelo:");

        textBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBrandActionPerformed(evt);
            }
        });

        textModel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        labelVehicleType.setText("Tipo vehiculo");

        labelExtras.setText("Extras:");

        checkBoxCoche.setText("Coche");
        checkBoxCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCocheActionPerformed(evt);
            }
        });

        checkBoxMoto.setText("Moto");
        checkBoxMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMotoActionPerformed(evt);
            }
        });

        checkBoxCamion.setText("Camión");
        checkBoxCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCamionActionPerformed(evt);
            }
        });

        checkBoxCapota.setText("Capota");
        checkBoxCapota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCapotaActionPerformed(evt);
            }
        });

        checkBoxSidecar.setText("Sidecar");
        checkBoxSidecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSidecarActionPerformed(evt);
            }
        });

        checkBoxRemolque.setText("Remolque");
        checkBoxRemolque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxRemolqueActionPerformed(evt);
            }
        });

        jButtonSend.setText("Enviar");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        buttonGroupFuel.add(jRadioButtonGasolina);
        jRadioButtonGasolina.setText("Gasolina");

        buttonGroupFuel.add(jRadioButtonDiesel);
        jRadioButtonDiesel.setText("Diesel");
        jRadioButtonDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDieselActionPerformed(evt);
            }
        });

        buttonGroupFuel.add(jRadioButtonElectrico);
        jRadioButtonElectrico.setText("Eléctrico");

        jComboBoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Amarillo", "Verde", "Azul" }));
        jComboBoxColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColorActionPerformed(evt);
            }
        });

        jTextFieldAlertMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlertMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(labelVehicleType)
                .addGap(100, 100, 100)
                .addComponent(labelExtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldAlertMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButtonSend))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(checkBoxMoto)
                                                    .addComponent(checkBoxCamion)
                                                    .addComponent(checkBoxCoche))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(checkBoxCapota)
                                                    .addComponent(checkBoxRemolque)
                                                    .addComponent(checkBoxSidecar)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(brandLabel)
                                                    .addComponent(labelModel))
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(textBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                    .addComponent(textModel)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonDiesel)
                                    .addComponent(jRadioButtonElectrico)
                                    .addComponent(jRadioButtonGasolina))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelTitle)
                .addGap(3, 3, 3)
                .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLabel)
                    .addComponent(textBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModel)
                    .addComponent(textModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVehicleType)
                    .addComponent(labelExtras)
                    .addComponent(jRadioButtonGasolina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxCoche)
                    .addComponent(checkBoxCapota)
                    .addComponent(jRadioButtonDiesel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxMoto)
                    .addComponent(checkBoxSidecar)
                    .addComponent(jRadioButtonElectrico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxCamion)
                    .addComponent(checkBoxRemolque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSend)
                    .addComponent(jTextFieldAlertMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCocheActionPerformed
        // TODO add your handling code here:
        checkBoxCoche.setSelected(true);
        checkBoxMoto.setSelected(false);
        checkBoxCamion.setSelected(false);
        checkBoxRemolque.setEnabled(true);           
        checkBoxCapota.setEnabled(true);
        checkBoxSidecar.setEnabled(false);
        checkBoxSidecar.setSelected(false);
        mensajeFinalVehiculo = mensajeFijoVehiculo + " coche";
    }//GEN-LAST:event_checkBoxCocheActionPerformed

    private void textBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBrandActionPerformed

    private void checkBoxSidecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSidecarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxSidecarActionPerformed

    private void checkBoxMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMotoActionPerformed
        // TODO add your handling code here:
        checkBoxCoche.setSelected(false);
        checkBoxMoto.setSelected(true);
        checkBoxCamion.setSelected(false);
        checkBoxRemolque.setEnabled(false);           
        checkBoxCapota.setEnabled(false);
        checkBoxSidecar.setEnabled(true);
        checkBoxRemolque.setSelected(false);           
        checkBoxCapota.setSelected(false);
        mensajeFinalVehiculo = mensajeFijoVehiculo + " moto";
        
    }//GEN-LAST:event_checkBoxMotoActionPerformed

    private void checkBoxCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCamionActionPerformed
        // TODO add your handling code here:
        checkBoxCoche.setSelected(false);
        checkBoxMoto.setSelected(false);
        checkBoxCamion.setSelected(true);
        checkBoxRemolque.setEnabled(true);           
        checkBoxCapota.setEnabled(false);
        checkBoxSidecar.setEnabled(false);
        checkBoxCapota.setSelected(false);
        checkBoxSidecar.setSelected(false);
        mensajeFinalVehiculo = mensajeFijoVehiculo + " camión";
    }//GEN-LAST:event_checkBoxCamionActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonDiesel.isSelected() || jRadioButtonElectrico.isSelected() || jRadioButtonGasolina.isSelected()){
            System.out.println(mensajeFinalVehiculo + ".");
            System.out.println("Marca: " + textBrand.getText());
            System.out.println("Modelo: " + textModel.getText());        
            if(checkBoxCapota.isSelected() || checkBoxRemolque.isSelected() || checkBoxSidecar.isSelected()){
                System.out.println(cabeceraExtras);
            }
            if(checkBoxCapota.isSelected()){
                System.out.println(mensajeCapota);
            }
            if(checkBoxSidecar.isSelected()){
                System.out.println(mensajeSidecar);
            }
            if(checkBoxRemolque.isSelected()){
                System.out.println(mensajeRemolque);
            }
            System.out.println("Color:");
            System.out.println(jComboBoxColor.getSelectedItem());
        } else {
            jTextFieldAlertMessage.setVisible(true);
            jTextFieldAlertMessage.setText(alertFuel);
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void checkBoxCapotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCapotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxCapotaActionPerformed

    private void checkBoxRemolqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxRemolqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxRemolqueActionPerformed

    private void jRadioButtonDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDieselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDieselActionPerformed

    private void jComboBoxColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxColorActionPerformed

    private void jTextFieldAlertMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlertMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlertMessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandLabel;
    private javax.swing.ButtonGroup buttonGroupFuel;
    private javax.swing.JCheckBox checkBoxCamion;
    private javax.swing.JCheckBox checkBoxCapota;
    private javax.swing.JCheckBox checkBoxCoche;
    private javax.swing.JCheckBox checkBoxMoto;
    private javax.swing.JCheckBox checkBoxRemolque;
    private javax.swing.JCheckBox checkBoxSidecar;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JComboBox<String> jComboBoxColor;
    private javax.swing.JRadioButton jRadioButtonDiesel;
    private javax.swing.JRadioButton jRadioButtonElectrico;
    private javax.swing.JRadioButton jRadioButtonGasolina;
    private javax.swing.JTextField jTextFieldAlertMessage;
    private javax.swing.JLabel labelExtras;
    private javax.swing.JLabel labelModel;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelVehicleType;
    private javax.swing.JTextField textBrand;
    private javax.swing.JTextField textModel;
    // End of variables declaration//GEN-END:variables
}
